### ISSUE TITLE
HELP!!!! MultiMC Not Worrking!

### ISSUE THREAD

**Issue by ZZManS** [nguyenq/lept4j#1]
MultiMC version: 0.4.10-733

Minecraft folder is:
instances/Zachary_S_Client/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/java.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2432m, -Duser.language=en, -jar, C:/Users/zzman/Documents/New folder/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 7272

Error occurred during initialization of VM
Could not reserve enough space for 2490368KB object heap
Process exited with code 1.

Don't know what to do

**Comment by 4F2E4A2E** [comment]
It could be related to lept4j or it could be many things, none of which related to lept4j.
Which Java Version? Do you have an example code for us which explain what you actually are trying to achieve?

**Comment by nguyenq** [comment]
Nothing seems to indicate this is related to the project at all.

**Comment by nguyenq** [comment]
Not related.
