### ISSUE TITLE
LineRemovalTest and image other than "dave-orig.png"

### ISSUE THREAD

**Issue by Artgit** [nguyenq/lept4j#11]
Hello,

I need to remove lines from my images. For this purpose, I'd like to use logic form the following example https://github.com/nguyenq/lept4j/blob/master/src/test/java/net/sourceforge/lept4j/LineRemovalTest.java but I'm unable to process any image other than 'dave-orig.png'. 

What can be a reason for this and how to apply this logic to other images?

Thanks

**Comment by nguyenq** [comment]
The code, adapted from the original C code example, works only with gray-scale images. You can see its effect on `table.png` sample image.

**Comment by Artgit** [comment]
Thanks! Could you please show how to rotate Pix with Lept4j on 90 degrees?

**Comment by nguyenq** [comment]
There's a native function for that. Check the [doc](http://tess4j.sourceforge.net/docs/index.html) for `pixRotate90`.

**Comment by Artgit** [comment]
Thank you very much for your help! I'm very new to this material. I apologize for the number of questions here, but I unable to get the answers in other places.

Currently, I'm trying to convert OpenCV Mat object to Pix. This is my current try:

	public static Pix matToPix(Mat mat) {
		
		if (mat == null) {
			throw new IllegalStateException("Recycled image");
		}

		final byte[] bytes = new byte[(int) mat.total()];
		
		mat.get(0, 0, bytes);
		
		ByteBuffer buff = ByteBuffer.wrap(bytes);
		return Leptonica1.pixReadMem(buff, new NativeSize(buff.capacity()));
	}

but unfortunately `matToPix `returns null.

What am I doing wrong?

**Comment by nguyenq** [comment]
Try this code:

    public static Pix convertMatToPix(Mat mat) {
        MatOfByte bytes = new MatOfByte();
        Imgcodecs.imencode(".tif", mat, bytes);
        ByteBuffer buff = ByteBuffer.wrap(bytes.toArray());
        return Leptonica1.pixReadMem(buff, new NativeSize(buff.capacity()));
    }

and its complement:

    public static Mat convertPixToMat(Pix pix) {
        PointerByReference pdata = new PointerByReference();
        NativeSizeByReference psize = new NativeSizeByReference();
        Leptonica1.pixWriteMem(pdata, psize, pix, ILeptonica.IFF_TIFF);
        byte[] b = pdata.getValue().getByteArray(0, psize.getValue().intValue());
        Leptonica1.lept_free(pdata.getValue());
        return Imgcodecs.imdecode(new MatOfByte(b), Imgcodecs.CV_LOAD_IMAGE_UNCHANGED);
    }

**Comment by shailendrabisht** [comment]
Hi @nguyenq  ,
This doesn't work for all grayscale images, pixThresholdToBinary method returns null for most of the greyscale images, as its native couldn't debug :(
Is there a way we can pre-process the greyscale image to use this function

**Comment by nguyenq** [comment]
@shailendrabisht You may want to repost your question to [Leptonica](https://github.com/DanBloomberg/leptonica) developers for advice.
