### ISSUE TITLE
BufferedImage to Pix, remove lines and Pix to BufferedImage 

### ISSUE THREAD

**Issue by Artgit** [nguyenq/lept4j#12]
I'm trying to convert BufferedImage to Pix, then remove lines and then convert Pix to BufferedImage.

This is my test `scanned-table.jpg` image:

![scanned-table](https://user-images.githubusercontent.com/2064812/36498369-c010ddb4-1746-11e8-9eba-f40171b32868.jpg)

This is the test code:

	BufferedImage bi = ImageIO.read(new File("scanned-table.jpg"));
	Pix pixs = LeptUtils.convertImageToPix(bi);
		
	Pix pixs1 = LeptUtils.removeLines(pixs);
	Pix pixs2 = Leptonica1.pixRotate90(pixs1, 1);
	Pix pixs3 = LeptUtils.removeLines(pixs2);
	Pix pixs4 = Leptonica1.pixRotate90(pixs3, -1);

	Leptonica instance = Leptonica.INSTANCE;
	instance.pixWrite("result.png", pixs4, ILeptonica.IFF_PNG);
		
	BufferedImage bufferedImage = LeptUtils.convertPixToImage(pixs4);
	System.out.println("bufferedImage: " + bufferedImage);

First of all the result.png looks damaged:

![result](https://user-images.githubusercontent.com/2064812/36498509-210baf5e-1747-11e8-82fd-0dcf82c1ef4a.png)

and also `LeptUtils.convertPixToImage(pixs4)` failed to convert `pixs4 `back to `BufferedImage `

What am I doing wrong and how to fix it? Thanks!

**Comment by nguyenq** [comment]
Can you attach `scanned-table.jpg` to the ticket?

**Comment by Artgit** [comment]
Sure, this is scanned-table.jpg:
![scanned-table](https://user-images.githubusercontent.com/2064812/36502470-bea2afd2-1752-11e8-9460-a3fcc8eb65e4.jpg)

this is the link on the internet of the same image: https://thewordmatrix.files.wordpress.com/2012/07/scanned-table.jpg?w=474&h=385

**Comment by nguyenq** [comment]
I got the same result with the image: lines were removed but text became smeared.

**Comment by Artgit** [comment]
@nguyenq another issue with this code that LeptUtils.convertPixToImage(pixs4); doesn't work properly for any of my test images and I'm unable to convert Pix back to BufferedImage. What may be wrong there?

**Comment by nguyenq** [comment]
It seems the round-trip conversion has issues, as mentioned in #10. It is caused by `Leptonica1.bbufferDestroy` statement in `LeptUtils.convertPixToImage` method. Removing it, however, would cause memory leaks. We're trying to determine what would be the optimal solution to this. Any suggestion is welcome.

**Comment by nguyenq** [comment]
A fix ff93f3030eaa7bdb578c931fccd4cd02d4af0181 has been committed for convertPixToImage issue.

**Comment by Artgit** [comment]
@nguyenq thank you very much! Is it possible to use lept4j-1.9.1 as Maven dependency? Is it available in any Maven repository on the internet?

**Comment by nguyenq** [comment]
It has just been released and is available on https://oss.sonatype.org now and on Central Maven shortly.

**Comment by Artgit** [comment]
@nguyenq thank you very much! It is working now!

**Comment by nguyenq** [comment]
Can this ticket be closed?

As to the problem of bad output image from line removal code, you may want to open a ticket with [Leptonica](https://github.com/DanBloomberg/leptonica) developers asking for advice.

**Comment by Artgit** [comment]
sure, thanks for your help on this issue!
