### ISSUE TITLE
lept4j Maven dependency on Linux

### ISSUE THREAD

**Issue by Artgit** [nguyenq/lept4j#13]
I'm trying to use the following lept4j Maven artifact:

		<dependency>
		    <groupId>net.sourceforge.lept4j</groupId>
		    <artifactId>lept4j</artifactId>
		    <version>1.9.0</version>
		</dependency>

Under the Windows, everything is working fine, but under the Linux, it fails with the following exception:

java.lang.UnsatisfiedLinkError: Unable to load library 'lept': Native library (linux-x86-64/liblept.so) not found in resource path

The Windows dll libraries are shipped inside of lept4j Maven artifact but  how to properly use lept4j on the Linux platform?

**Comment by nguyenq** [comment]
If you read the release notes, you'll notice that 1.9.0 is for Leptonica 1.75.3. Is that the version of Leptonica you're having on your Linux box?

**Comment by Artgit** [comment]
Yes, it was the issue. I have reinstalled Leptonica 1.75.3 and now everything works fine.
