### ISSUE TITLE
Problem with Java 9: Maven: com.github.jai-imageio:jai-imageio-core:1.3.1

### ISSUE THREAD

**Issue by RaiMan** [nguyenq/lept4j#16]
Your dependency has problems with the new Java versioning system. They currently try to update to 1.3.2, but it hangs since a month (problems with TravisCI). 

Please be prepared to update your dependency to 1.3.2, when they are ready.

I have the problem fixed for now in my local development by overwriting the 1.3.1 version with a working patched version of 1.3.2-SNAPSHOT in my local repo.

I am using Tess4J. Thanks for your work.

**Comment by nguyenq** [comment]
Thanks for the heads-up. We'll update when jai-imageio-core-1.3.2 is published.

**Comment by nguyenq** [comment]
Fixed in lept4j-1.6.4 & lept4j-1.9.3 releases.
