### ISSUE TITLE
Error when removing lines from image

### ISSUE THREAD

**Issue by Degubi** [nguyenq/lept4j#17]
I get no image output/any errors in console when using this code with my own image.
Works fine with dave-orig.png from the test code or scanned-table.jpg from https://github.com/nguyenq/lept4j/issues/12

Code:

     var file = Leptonica1.pixRead("bordered.png");
     var pixs1 = LeptUtils.removeLines(file);
     var pixs2 = Leptonica1.pixRotate90(pixs1, 1);
     var pixs3 = LeptUtils.removeLines(pixs2);
     var pixs4 = Leptonica1.pixRotate90(pixs3, -1);

     Leptonica1.pixWrite("result.png", pixs4, ILeptonica.IFF_PNG);

Image:
![bordered](https://user-images.githubusercontent.com/13366932/72218039-8b4ff280-3536-11ea-98fb-3ca5fa1267b6.png)

**Comment by nguyenq** [comment]
The Line Removal algorithm only works with gray-scale images.

**Comment by Degubi** [comment]
That explains everything @nguyenq , thank you!

**Comment by Degubi** [comment]
Converted image to greyscale, works as intented. :) Thank you @nguyenq
