### ISSUE TITLE
I can't get result of pixOtsuAdaptiveThreshold

### ISSUE THREAD

**Issue by sbrassely** [nguyenq/lept4j#3]
Hi,

When playing with the OtsuAdaptiveMethod from leptonica, I can not recover the output image with this code :
`PointerByReference ppixth= new PointerByReference();`
`PointerByReference ppixd= new PointerByReference();`
`int pix1 = instance.pixOtsuAdaptiveThreshold(result3, 2000, 2000, 0, 0, 0.0F, ppixth, ppixd);`
`Pix p2 = new Pix(ppixd.getPointer());`

Althought pix1 value is 0 (meaning that the treatment was successful), I always get this exception :
`Caused by: java.lang.IndexOutOfBoundsException: Bounds exceeds available space : size=8, offset=64
    at com.sun.jna.Memory.boundsCheck(Memory.java:203)
    at com.sun.jna.Memory.share(Memory.java:131)
    at com.sun.jna.Structure.useMemory(Structure.java:332)`

Is there something I miss in my code ?

Thanks for your response

**Comment by nguyenq** [comment]
Should be `Pix p2 = new Pix(ppixd.getValue());`. See the [unit test](https://github.com/nguyenq/lept4j/blob/master/src/test/java/net/sourceforge/lept4j/OtsuTest.java).

**Comment by sbrassely** [comment]
Oh yes you're right.
The PointerByReference getPointer method made me wrong.
Sorry about that
