### ISSUE TITLE
Compile Lept4J for Linux

### ISSUE THREAD

**Issue by joshimar** [nguyenq/lept4j#6]
Hi!

I downloaded your source codej and ran **mvn install** to get a fresh build of Lept4J.

The thing is that the jar comes with windows native libraries, if you type **jar tf  lept4j-master/target/lept4j-1.2.5-SNAPSHOT.jar** you will see the .dll libraries under win32-x86 and win32-x86. 

I need to generate exactly the same jar but without these 2 directories and put my own Leptonica .so libraries under a directory called linux-86-64.

Do you know how to do this?
Thanks a lot!

**Comment by nguyenq** [comment]
JNA searches for the packaged native library under specific folder depending on the OS architecture (see [`Platform.java`](https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/Platform.java)). So for Linux, place your `liblept.so` under either `linux-x86` or `linux-x86-64` directory, depending on the bitness.

**Comment by joshimar** [comment]
Thanks @nguyenq !

Now, I put my **linux-x86-64/liblept.so** inside **lept4j-master\src\main\resources**, but after doing this and **mvn install**, I just see inside the generated jar the win32-x86 and win32-x86 directories, not linux-x86 or linux-x86-64. 

Do I need to add something to the pom.xml or any other configuration so I can get rid of the Windows' libraries and add my Linux ones besides placing them under the mentioned directory?

**Comment by nguyenq** [comment]
I did the same test. After `mvn install`, check the local `m2` repository, and found the generated `lept4j-1.2.5-SNAPSHOT.jar` containing `liblept.so` file under `linux-x86` directory.

**Comment by joshimar** [comment]
Thank you so much @nguyenq !
