### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/sourceforge/lept4j/Boxa : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by SylvesterJo** [nguyenq/lept4j#9]
I checked the Manifest file after extracting the lept4j jar and see the below information - 

Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.6
Created-By: 1.8.0_91-b14 (Oracle Corporation)
Class-Path: lib/rococoa-core-0.5.jar lib/jai-imageio-core-1.3.1.jar li
b/commons-io-2.5.jar lib/jna-4.1.0.jar
X-COMMENT: Main-Class will be added automatically by build

This suggests that the jar is built using Java 1.8. Is their a version of lept4j created in Java 1.7, as my project follows a standard to use nothing higher than Java 1.7.

Any help would be highly appreciated.

Thanks
Sylvester J.

**Comment by nguyenq** [comment]
Yes, it was compiled with JDK 1.8. To the best of my recollection, the library is not using any Java 1.8-specific API, so you can certainly rebuild it with JDK 1.7, which a developer successfully did [recently](https://sourceforge.net/p/tess4j/discussion/1202293/thread/b34115e7/).

We probably will downgrade to JDK 1.7 for the next release to accommodate larger user base.

Thanks.

**Comment by SylvesterJo** [comment]
I checked the jars being used by the tess4j jna wrapper like lept4j, tess4j, jna, etc. All have the manifest saying these have been compiled using Java 1.8. So kindly suggest will I have to get the source Java files for these and recompile these with Java 1.7 to make this exception go away?

Regards
Sylvester

**Comment by nguyenq** [comment]
All of them are available right here on github. lept4j and tess4j are straighforward to build using Maven. I can't speak for jna, though.

Quan

**Comment by nguyenq** [comment]
1.3.1 has been compiled using JDK 1.8 but targeted to 1.7.
